### ISSUE TITLE
Typo in first paragraph

### ISSUE THREAD

**Issue by jonrobinson2** [JessicaGarson/Whats-my-function-3#1]
Just getting started but saw a typo and figured I'd contribute because Github (why else not!).

One sentence is:

"I often get questions from new programmers who looking to create a personal site"

Should be:

"I often get questions from new programmers who **are** looking to create a personal site"

**Comment by JessicaGarson** [comment]
Thanks! Will update shortly :)

You are awesome.

**Comment by jonrobinson2** [comment]
:)

**Comment by JessicaGarson** [comment]
Fixed :)
